### ISSUE TITLE
Database Schema model

### ISSUE THREAD

**Issue by AntoineDao** [pollination/model-service#2]
We need an SQL alchemy (or other) schema model to be used to input data into a database.

**Comment by AntoineDao** [comment]
@mostaphaRoudsari would you mind jotting down what you expect the database schema to look like? 

Something along the lines of:

## Table 1 - Model
|  id |  name |  creator_id |  created_at |   updated at|
|--:|---|---|---|---|
|  unique uui | descriptive name - default none  |  id of creator |  date created |  date updated |

## Table 2 - Surfaces
|  id  |  model_id | geometry  | material  | created_at  |
|--:|---|---|---|---|
|  surface id |  id of the model to index it to  | geometry json  |  material json |  date created |

**Comment by mostaphaRoudsari** [comment]
For model table I was thinking to follow an [event sourcing pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing) to be able to keep track of changes by different users and different changes over time. We can have a separate table for `actions` later where we log more details for each action. For now we will know who has done what and when. Something like this:

```Python
class Model(Base):
    """Pollination model schema."""
    __tablename__ = 'model'
    id = sa.Column(sa.String, primary_key=True, default=str(uuid.uuid4()))
    name = sa.Column(sa.String, nullable=False)
    convert_to_meters = sa.Column(sa.Numeric, default=1.0)
    user_id = sa.Column(sa.Integer, nullable=False, default=False)
    timestamp = sa.Column(sa.DateTime, nullable=False,
        default=datetime.datetime.utcnow())
    # created, updated, deleted
    action = sa.Column(sa.String, nullable=False, default=False) 
```

For Face (not Surface!) table I think we should expose the type. `FACE`, `APERTURE`, `SHADE` and remove name and material. Material will be part of the Face data so it should not be a separate column and the material information is a reference not a full material definition. You will also need tables for `vertices` and `rad_modifiers`. I assume that they will be similar to sensor.

```Python
class Face(Base):
    """Face Model for storing faces."""
    __tablename__ = 'face'
    id = sa.Column(sa.Integer,  primary_key=True)
    model_id = sa.Column(sa.String, sa.ForeignKey('model.id'))
    timestamp = sa.Column(sa.DateTime, nullable=False,
        default=datetime.datetime.utcnow())
    # FACE, APERTURE, SHADE
    type = sa.Column(sa.String, nullable=False, default=False) 
    face = sa.Column(sa.JSON)

class Vertex(Base):
    """Vertex Model for storing vertices."""
    __tablename__ = 'vertex'
    gid = sa.Column(sa.Integer, primary_key=True)
    id = sa.Column(sa.Integer)
    model_id = sa.Column(sa.String, sa.ForeignKey('model.id'))
    x = sa.Column(sa.Numeric, nullable=False)
    y = sa.Column(sa.Numeric, nullable=False)
    z = sa.Column(sa.Numeric, nullable=False)

class RadModifier(Base):
    """Vertex Model for storing vertices."""
    __tablename__ = 'radmodifier'
    gid = sa.Column(sa.Integer, primary_key=True)
    id = sa.Column(sa.Integer)
    model_id = sa.Column(sa.String, sa.ForeignKey('model.id'))
    material = sa.Column(sa.JSON)
```

We will still be missing dynamic faces which are also models and energyplus related stuff (zone, ep construction) which is post MVP.

**Comment by mostaphaRoudsari** [comment]
PS: This schema is based on `Model` and not `FaceByFaceModel`. `FaceByFaceModel` will be converted to `Model` before being stored.

**Comment by AntoineDao** [comment]
Had a wee read through event sourcing stuff. It sounds super interesting however I don't think the implementation you propose here works. The `event-store` they describe here is a completely separate table that is used like a sort of log which is then used to materialise the object. 

In our case this would mean two things:
1. The model table would have to contain a persistent `model_id` column so we would know which model to resolve all changes against
2. Each row of changes would have to contain all the changes in a given row or we will have to manage event across multiple tables, which would add a maaaaassive overhead of work on the microservice side.

A table row would look something like this for a payload oriented:

| id | model_id | name | convert_to_meters | user_id | timestamp | action | event_payload |
|---|-------------|--------|--------------------|---------|--------------|------|-------------------|
| event id | persistent model id| model name| ... | ... | ...| created/updated/deleted  | {deleted_faces: [ list of ids ], updated_faces: [ list of ids]}  | 

Don't get me wrong, I think this is interesting and worth a look. But not for MVP. Let's stick to simple CRUD for the sake of getting something out of the door. Does this sound acceptable?

**Comment by AntoineDao** [comment]
Also, what's the `gid` column for the Face, Vertex and Radmodifier tables?
